- name: Install the Apache mod_security2 module
  apt:
    pkg: 
     - "libapache2-mod-security2"
    update_cache: yes
    state: latest

- name: enable mod_security2
  apache2_module:
    name: security2
    state: present
  notify:
   - restart apache2

- name: enable headers module
  apache2_module:
    state: present
    name: headers
  notify:
  - restart apache2

- name: Deploy modsecurity.conf file
  template:
    src: "modsecurity2.conf.j2"
    dest: "{{ apache_conf_dir }}/modsecurity.conf"
    owner: root
    group: root
    mode: 0644

# a2enconf modsecurity.conf
- name: enable mod_securit2 config file
  command: "a2enconf modsecurity.conf"
  notify:
  - restart apache2
    