- name: Add MaxMind GeoIP repository
  apt_repository:
    repo: ppa:maxmind/ppa

- name: Install GeoIP Update
  apt:
    pkg: 
     - "geoipupdate"
    update_cache: yes
    state: latest

- name: Deploy GeoIP Configuration
  template:
    src: "GeoIP.conf"
    dest: "/etc/"
    owner: root
    group: root
    mode: 0644

- name: Update GeoIP Database
  command: 
    cmd: geoipupdate

- name: Install the Apache mod_security2 module
  apt:
    pkg: 
     - "libapache2-mod-security2"
    update_cache: yes
    state: latest

- name: Download CRS core rule set
  git:
    repo: 'https://github.com/coreruleset/coreruleset.git'
    dest: /usr/share/coreruleset
    update: true
    force: true

- name: Remove file REQUEST-922-MULTIPART-ATTACK.conf
  file:
    path: /usr/share/coreruleset/rules/REQUEST-922-MULTIPART-ATTACK.conf
    state: absent

- name: Download CRS core wordpress plugin
  git:
    repo: 'https://github.com/coreruleset/wordpress-rule-exclusions-plugin.git'
    dest: /usr/share/coreruleset-wordpress
    update: true
    force: true

- name: Copy CRS core wordpress plugin into plugins dir
  copy:
    src: /usr/share/coreruleset-wordpress/plugins/
    remote_src: true
    dest: /usr/share/coreruleset/plugins/
    mode: '0644'

- name: Enable mod_security2
  apache2_module:
    name: security2
    state: present
  notify:
   - restart apache2

- name: Enable headers module
  apache2_module:
    state: present
    name: headers
  notify:
  - restart apache2

- name: Deploy modsecurity.conf file
  template:
    src: "modsecurity2.conf.j2"
    dest: "{{ apache_conf_dir }}/modsecurity.conf"
    owner: root
    group: root
    mode: 0644

- name: Deploy modsecurity module config file security2.conf
  template:
    src: "security2.conf.j2"
    dest: "{{ apache_module_dir }}/security2.conf"
    owner: root
    group: root
    mode: 0644

- name: Copy crs-setup file from git repo
  ansible.builtin.copy:
    src: /usr/share/coreruleset/crs-setup.conf.example
    remote_src: true
    dest: /etc/modsecurity/crs/crs-setup.conf
    mode: '0644'

- name: Enable modsecurity config file
  command: "a2enconf modsecurity.conf"
  notify:
  - restart apache2