---

- name: Update stuff
  hosts: ubuntu
  vars_files: vars/ubuntu.yaml
  roles:
    - volumes
    - hostname
    - update
    - tools
    - mysql
    - wordpress
    - { role: geerlingguy.certbot }
    - { role: geerlingguy.apache }
    - modsecurity
    - htaccess
    - apparmor
    - minio
    - dropbox
    - systemd
  become: true
  become_user: root