
- file:
    path: "/home/{{ mc_user }}/.aws"
    state: directory
    owner: "{{ mc_user }}"
    group: "{{ mc_user }}"
    mode: 0600
  
- copy:
    content: |
            [default]
            region = eu-west-2
    dest: "/home/{{ mc_user }}/.aws/config"
    owner: "{{ mc_user }}"
    group: "{{ mc_user }}"
    mode: 0600

- copy:
    content: |
            [default]
            aws_access_key_id = {{ lookup('amazon.aws.aws_secret', '{{ aws_user_role }}.aws_access_key_id', nested=True) }}
            aws_secret_access_key = {{ lookup('amazon.aws.aws_secret', '{{ aws_user_role }}.aws_secret_access_key', nested=True) }}
    dest: "/home/{{ mc_user }}/.aws/credentials"
    owner: "{{ mc_user }}"
    group: "{{ mc_user }}"
    mode: 0600